### ISSUE TITLE
Catch 403 error

### ISSUE THREAD

**Issue by pmast** [google/fusion-tables-archive-visualizer#10]
There is a 403 error thrown most times:

![image](https://user-images.githubusercontent.com/2733607/65857045-57740700-e363-11e9-9a85-ae9b6c2dbafe.png)

It seems that this error is part of an additional request that we make… If this is the result of a regular request we should better catch it and keep the console clean.

**Comment by hundekoerper** [comment]
I don't think that's possible. We don't log or throw these errors programmatically. It's Chrome default behavior (these errors don't show up in Firefox) to log http client error status codes (4XX) to the console.
