### ISSUE TITLE
SSL issue: The hyperlink in the README doesn't work

### ISSUE THREAD

**Issue by krzysztofspilka** [google/fusion-tables-archive-visualizer#3]
Hey guys! I just tried to open https://geoviz.fusiontables-archive.withgoogle.com/ but there is a problem with your SSL certificate, hence the browser refuses to take me to the page.

![Screen Shot 2019-09-11 at 15 58 27](https://user-images.githubusercontent.com/8048526/64703607-164bae00-d4ad-11e9-936a-57de206b98f4.png)

**Comment by russellquong** [comment]
Whoops.  That link is incorrect.   I'll work on correcting that.

The README should tell you to look at the `ft-archive-index` Sheet in Drive
which links to your visualizations.

**Comment by siccovansas** [comment]
The incorrect link is still in the README.
