### ISSUE TITLE
No geometry found

### ISSUE THREAD

**Issue by rkr327** [google/fusion-tables-archive-visualizer#6]
Hello, when I use the archive tool with my fusion table of about 1300 locations, the tool says "no geometry found." How to I get the tool to reproduce my map visualization?

Thanks,

Ryan

**Comment by pmast** [comment]
Hi Ryan,

thanks for reaching out.
It is hard to determine what the geometry columns are in a fusion table as the columns are not labeled/tagged. Therefore the tool uses some heuristics to determine the geometry columns.

The simplest heuristics are:
- `latitude`/`longitude` columns for point data in lat/lng format
- a `geometry` column for geometries

**Comment by rkr327** [comment]
Reformatting the spreadsheet that way did the trick! Thanks so much.

**Comment by pmast** [comment]
You are welcome. We hope to make it more robust to those issues in the future!
